menu:
    Blog: /
    Archive: /archives/
    Links: /friends/
    GitHub: https://github.com/coolrc136
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
#disqus:
#duoshuo: coolrc
gitment: 
    repo: blog_comment
    id: coolrc136
    clientid: 54a5c97e9smfbhkrn
    clientsecret: 475f010e505sbvhsdbkfsbrno

gitalk: 
    repo: blog_comment
    id: coolrc136
    clientid: 54a5c97e9smfbhkrn
    clientsecret: 475f010e505sbvhsdbkfsbrno

# Analytics
# google-analytics:
ga: UA-71skjfks

# Copyright Infomation
startyear: 2015

# ICP备案
icp:
    link: http://www.miitbeian.gov.cn/
    code: 陕ICP备19007986号
